# Generated by Django 4.0.3 on 2022-04-11 01:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('pay_range', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resume_groomed', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
