# Generated by Django 4.0.3 on 2022-04-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.job'),
            preserve_default=False,
        ),
    ]
